### ISSUE TITLE
Broken after Mouhijoki 2.2.0.29 update

### ISSUE THREAD

**Issue by Termitebug** [kimmoli/usbdisk-utils#1]
External USB memory drives (sticks, cards, etc) doesn't mount automatically and are not seen in the filesystem.
Tested with Xperia X and Jolla Tablet.

**Comment by kimmoli** [comment]
Thanks for reporting

**Comment by kimmoli** [comment]
usbstick-utils works for me on Onyx on Mouhijoki.
However i noticed sd-utils is obsolete, so i modified usbstick-utils to use same services. Please see built package at OR, or here branch udisks

**Comment by kimmoli** [comment]
Please remove this with Mouhijoki or later. System sd-utils (or its replacement should support USB Disks.
